FROM ubuntu:latest

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libacl1-dev
RUN apt-get install -y libattr1-dev
RUN apt-get install -y libblkid-dev
RUN apt-get install -y libgnutls28-dev
RUN apt-get install -y libreadline-dev
RUN apt-get install -y python-dev
RUN apt-get install -y python-dnspython
RUN apt-get install -y gdb
RUN apt-get install -y pkg-config
RUN apt-get install -y libpopt-dev
RUN apt-get install -y libldap2-dev
RUN apt-get install -y dnsutils
RUN apt-get install -y libbsd-dev
RUN apt-get install -y attr
RUN apt-get install -y krb5-user
RUN apt-get install -y docbook-xsl
RUN apt-get install -y libcups2-dev
RUN apt-get install -y libavahi-client-dev
RUN apt-get install -y libavahi-common-dev
RUN apt-get install -y libacl1-dev
RUN apt-get install -y libldap2-dev
RUN apt-get install -y libgnutls28-dev
RUN apt-get install -y libgpgme11-dev
RUN apt-get install -y libjson-perl
RUN apt-get install -y libpam0g-dev
RUN apt-get install -y libarchive-dev
RUN apt-get install -y perl
RUN apt-get install -y libfam-dev
RUN apt-get install -y libnss-winbind
RUN apt-get install -y libpam-winbind
RUN apt-get install -y libdcerpc-dev
RUN apt-get install -y libtask-spooler-dev
RUN apt-get install -y libtevent-dev
RUN apt-get install -y libwbclient-dev
RUN apt-get install -y libtalloc-dev
RUN apt-get install -y libtdb-dev
RUN apt-get install -y libldb-dev
RUN apt-get install -y libcephfs-dev
RUN apt-get install -y libcephfs1
RUN apt-get install -y librados-dev
RUN apt-get install -y librados2
RUN apt-get install -y librbd-dev
RUN apt-get install -y librbd1
RUN apt-get install -y libcap-dev
RUN apt-get install -y libcephfs-java
RUN apt-get install -y librados2-java
RUN apt-get install -y libradosstriper-dev
RUN apt-get install -y libradosstriper1
RUN apt-get install -y libcephfs1-java
RUN apt-get install -y libcephfs-jni
RUN apt-get install -y libtevent0
RUN apt-get install -y libwbclient0
RUN apt-get install -y samba-dsdb-modules
RUN apt-get install -y libldb1
RUN apt-get install -y python-ldb
RUN apt-get install -y python-tdb
RUN apt-get install -y tdb-tools
RUN apt-get install -y python-crypto
RUN apt-get install -y python-ntdb
RUN apt-get install -y python-talloc
RUN apt-get install -y python-tdb-dev
RUN apt-get install -y python-gpgme
RUN apt-get install -y python3-gpgme
RUN apt-get install -y libgpgme-dev
RUN apt-get install -y python3-dev
RUN apt-get install -y python3-dnspython
RUN apt-get install -y python3-crypto
RUN apt-get install -y python3-talloc
RUN apt-get install -y python3-tdb
RUN apt-get install -y python3-gpgme
RUN apt-get install -y python3-gpg
RUN apt-get install -y python3-gpgconf
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3-gpgme-doc
RUN apt-get install -y python3-gpgme-dbg
RUN apt-get install -y python3-gpgme-dev
RUN apt-get install -y python3

RUN wget https://download.samba.org/pub/samba/stable/samba-4.14.6.tar.gz
RUN tar -xvf samba-4.14.6.tar.gz
RUN cd samba-4.14.6
RUN ./configure --enable-debug --enable-selftest \
        --with-modulesdir=/usr/lib/x86_64-linux-gnu/samba \
        --with-lockdir=/var/run/samba \
        --with-piddir=/var/run/samba \
        --with-privatedir=/etc/samba \
        --with-systemd \
        --with-cluster-support \
        --with-acl-support \
        --with-shared-modules=idmap_ad,idmap_rid,idmap_adex,idmap_hash,idmap_tdb2,vfs_default_quota,vfs_fruit,vfs_glusterfs,vfs_shadow_copy2,vfs_streams_depot \
        --with-ldap \
        --with-ads \
        --with-gpgme \
        --with-avahi \
        --with-pam \
        --with-quotas \
        --with-syslog \
        --with-utmp \
        --with-dnsupdate \
        --with-json-audit \
        --with-socket-wrapper \
        --with-libsmbclient \
        --with-winbind \
        --with-automount \
        --with-pie \
        --with-tdb \
        --with-ldb \
        --with-system-mitkrb5 \
        --with-system-mitkrb5crypto \
        --with-system-gssapi-h \
        --with-system-gcrypt \
        --with-system-unwind \
        --with-system-mitkrb5 \
        --with-system-mitkrb5crypto \
        --with-system-gssapi \
        --with-system-libtirpc \
        --with-system-pie \
        --with-system-tdb \
        --with-system-ldb \
        --with-system-libtasn1 \
        --with-system-heimdal-kcm \
        --with-system-heimdal-gssapi \
        --with-system-heimdal-hcrypto \
        --with-system-heimdal-roken \
        --with-system-heimdal-compat \
        --with-system-heimdal-asn1 \
        --with-system-heimdal-krb5 \
        --with-system-heimdal-krb5support \
        --with-system-heimdal-krb5types \
        --with-system-heimdal-krb5asn1 \
        --with-system-heimdal-krb5crypto \
        --with-system-heimdal-krb5rcache \
        --with-system-heimdal-krb5plugin \
        --with-system-heimdal-krb5kdc \
        --with-system-heimdal-krb5admin \
        --with-system-heimdal-krb5rpc \
        --with-system-heimdal-kdc \
        --with-system-heimdal-rt \
        --with-cluster-support 
RUN make -j8
RUN make install
RUN cd .. && rm -rf samba-4.14.6.tar.gz samba-4.14.6

